version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: "xm_app"
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=quotedata
      - APP_NAME=XMQuote
      - APP_ENV=local
      - APP_KEY=base64:vCNx/6gpVsHaJMc8YxPTuirLFUWLx1bbdmZVlqQaBGU=
      - APP_DEBUG=true
      - LOG_CHANNEL=stack
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=quotedata
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.googlemail.com
      - MAIL_PORT=465
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_ENCRYPTION=ssl
      - JWT_SECRET=pU6vnZIya0PfEOENr8dMkxiJO3lZ6FnDETHOW5TYe2Nzgm7JNX6rY4AO7yhIw72Y
    tty: true
    volumes:
        - ./backend:/var/www

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "xm_webserver"
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "4431:443"
    volumes:
        - ./backend:/var/www
        - ./backend/docker/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:5.7.22
    environment:
      - MYSQL_DATABASE=quotedata
      - MYSQL_ROOT_PASSWORD=password
    container_name: "xm_db"
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    volumes:
        - dbdata:/var/lib/mysql
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    
volumes:
   dbdata:
       driver: local

